### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by samitkapoor** [muhammedanaskhan/css-tricks#4]
It would be better if this repo has documentation for each css-trick, that shows the details of the effect below the code. So that the viewer doesn't have to run each code to see the effect.

**Comment by samitkapoor** [comment]
May I work on this issue? @muhammedanaskhan

**Comment by CrazeDoc** [comment]
Hey man, that's a great idea! I'm also interested in working on the same!

Let's start doing this!!!

**Comment by muhammedanaskhan** [comment]
That's a great idea @samitkapoor . Go on with it.

**Comment by samitkapoor** [comment]
Sure @muhammedanaskhan!
I'll start the work on it.
