### ISSUE TITLE
Updating the README with more details & adding a root HTML file for Github Pages

### ISSUE THREAD

**Issue by CrazeDoc** [muhammedanaskhan/css-tricks#5]
Hey, @muhammedanaskhan I was thinking of actively doing contributions to this repo to sharpen my CSS skills + Get started with doing some open-source contributions.

This would be a very small one but I want to bring in some cool stuff and actively document it in this repo!!

Need your permission for doing so! Shall I start working on this @muhammedanaskhan? 😅

**Comment by muhammedanaskhan** [comment]
You may do Aakash

**Comment by CrazeDoc** [comment]
Sure @muhammedanaskhan, will start working on it! 😊
